name: dl_prj_env

channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip=25.0
  - pytorch>=2.5.1
  - torchvision>=0.20.1
  - torchaudio>=2.5.1
  - pytorch-cuda=12.4
  - pip:
      - optuna==4.2.1
      - torchmetrics==1.7.0
      - albumentations==2.0.5
      - tqdm==4.67.1
      - Pillow==10.1.0
      - numpy==2.2.4
      - segmentation-models-pytorch==0.4.0
      - loguru==0.7.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - opencv-python==4.11.0.86
      - ptflops==0.7.4